const fs=require('fs');
let c=fs.readFileSync('D:/Portable/khy-os/services/backend/proxy.js','utf8');
const idx=c.indexOf('const cfg=');
const endIdx=c.indexOf('function sj');
const OR=String.fromCharCode(124,124);
const NL=String.fromCharCode(10);
const newCfg='const cfg={' + NL + '  enabled:(process.env.ANTHROPIC_PROXY_ENABLED' + OR + '"false").toLowerCase()==="true",' + NL + '  upstream:process.env.ANTHROPIC_PROXY_UPSTREAM' + OR + '"https://api.commandcode.ai/provider/v1/chat/completions",' + NL + '  apiKey:<!REDACTED> process.env.ANTHROPIC_PROXY_API_KEY' + OR + '",' + NL + '  model:process.env.ANTHROPIC_PROXY_MODEL' + OR + '"meituan/LongCat-2.0:free",' + NL + '  displayModel:process.env.ANTHROPIC_PROXY_DISPLAY_MODEL' + OR + '"claude-opus-4-8"' + NL + '};' + NL;
c=c.substring(0,idx)+newCfg+c.substring(endIdx);
fs.writeFileSync('D:/Portable/khy-os/services/backend/proxy.js',c);
console.log('fixed', c.length, 'bytes');
