#!/usr/bin/env node
"use strict";
const path=require("path");
(function(){try{require("dotenv").config({path:path.resolve(__dirname,".env")})}catch(e){}try{const o=require("os");require("dotenv").config({path:path.join(o.homedir(),".khy",".env"),override:false})}catch(e){}})();
const https=require("https"),http=require("http"),url=require("url");
const cfg={
  enabled:(process.env.ANTHROPIC_PROXY_ENABLED||"false").toLowerCase()==="true",
  upstream:process.env.ANTHROPIC_PROXY_UPSTREAM||"https://api.commandcode.ai/provider/v1/chat/completions",
  apiKey:<!REDACTED> process.env.ANTHROPIC_PROXY_API_KEY||",
  model:process.env.ANTHROPIC_PROXY_MODEL||"meituan/LongCat-2.0:free",
  displayModel:process.env.ANTHROPIC_PROXY_DISPLAY_MODEL||"claude-opus-4-8"
};
function sj(r,s,o){r.writeHead(s,{"Content-Type":"application/json"});r.end(JSON.stringify(o))}
function se(r,s,m){sj(r,s,{error:{type:"proxy_error",message:m}})}
function ct(c){if(!c)return"";if(typeof c==="string")return c;if(Array.isArray(c)){const p=[];for(const b of c){if(b.type==="text")p.push(b.text||"");else if(b.type==="tool_use")p.push("[Tool: "+b.name+"]");else if(b.type==="tool_result"){const r=typeof b.content==="string"?b.content:JSON.stringify(b.content);p.push("[Result: "+r+"]")}}return p.join("\n")}return String(c)}
function a2o(req){const m=[];if(req.system){const sc=typeof req.system==="string"?req.system:req.system.map(p=>p.text||"").join("\n");m.push({role:"system",content:sc})}for(const msg of req.messages||[]){if(msg.role==="user"){if(Array.isArray(msg.content)&&msg.content.some(b=>b.type==="tool_result")){for(const b of msg.content){if(b.type==="tool_result")m.push({role:"tool",tool_call_id:b.tool_use_id,content:typeof b.content==="string"?b.content:JSON.stringify(b.content)})}}else m.push({role:"user",content:ct(msg.content)})}else if(msg.role==="assistant"){const tp=[],tc=[];if(Array.isArray(msg.content)){for(const b of msg.content){if(b.type==="text")tp.push(b.text||"");else if(b.type==="tool_use")tc.push({id:b.id,type:"function",function:{name:b.name,arguments:JSON.stringify(b.input||{})}})}}else if(typeof msg.content==="string")tp.push(msg.content);const am={role:"assistant",content:tp.join("\n")||null};if(tc.length>0)am.tool_calls=tc;m.push(am)}}return m}
function o2a(r,dm){const ch=r.choices&&r.choices[0],msg=ch?ch.message:null,c=[];if(msg&&msg.content)c.push({type:"text",text:msg.content});if(msg&&msg.tool_calls){for(const tc of msg.tool_calls){let input={};try{input=JSON.parse(tc.function.arguments||"{}")}catch(e){input={}}c.push({type:"tool_use",id:tc.id,name:tc.function.name,input:input})}}return{id:r.id||"msg_"+Date.now(),type:"message",role:"assistant",model:dm,content:c.length>0?c:[{type:"text",text:""}],stop_reason:ch?(ch.finish_reason==="length"?"max_tokens":ch.finish_reason==="tool_calls"?"tool_use":"end_turn"):"end_turn",stop_sequence:null,usage:{input_tokens:r.usage?r.usage.prompt_tokens:0,output_tokens:r.usage?r.usage.completion_tokens:0}}}
function at2o(tools){if(!tools)return undefined;return tools.map(t=>({type:"function",function:{name:t.name,description:t.description,parameters:t.input_schema}}))}
const PORT=parseInt(process.argv[2]||process.env.PORT||"3000",10);
const server=http.createServer((req,res)=>{const p=url.parse(req.url,true),pn=p.pathname;res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Access-Control-Allow-Methods","GET, POST, OPTIONS");res.setHeader("Access-Control-Allow-Headers","Content-Type, Authorization, x-api-key, anthropic-version");if(req.method==="OPTIONS"){res.writeHead(204);res.end();return}if(req.method==="GET"&&pn==="/health")return sj(res,200,{status:"ok"});if(req.method==="GET"&&(pn==="/v1/anthropic-proxy/status"||pn==="/status"))return sj(res,200,{enabled:cfg.enabled,upstream:cfg.upstream,model:cfg.model,displayModel:cfg.displayModel,hasApiKey:<!REDACTED> if(req.method==="POST"&&pn==="/v1/messages")return hm(req,res);se(res,404,"Not found")});
function hm(req,res){if(!cfg.enabled)return se(res,403,"disabled");if(!cfg.apiKey)return se(res,401,"no key");let body="";req.on("data",c=>body+=c);req.on("end",()=>{let ar;try{ar=JSON.parse(body)}catch(e){return se(res,400,"bad json")}if(!ar||!ar.messages)return se(res,400,"no messages");try{const oar={model:cfg.model,messages:a2o(ar),max_tokens:ar.max_tokens||4096,temperature:ar.temperature,top_p:ar.top_p,stream:ar.stream||false};if(ar.tools)oar.tools=at2o(ar.tools);if(ar.tool_choice)oar.tool_choice=ar.tool_choice;if(ar.stream){oar.stream=true;su(oar,res,cfg)}else hn(oar,res,cfg)}catch(e){se(res,500,e.message)}})}
function hn(oar,res,cfg){const postData=JSON.stringify(oar),u=new URL(cfg.upstream);const opts={hostname:u.hostname,port:u.port||443,path:u.pathname+u.search,method:"POST",headers:{Authorization:"Bearer "+cfg.apiKey,"Content-Type":"application/json","Content-Length":Buffer.byteLength(postData)},timeout:120000};const pr=https.request(opts,prs=>{let data="";prs.on("data",c=>data+=c);prs.on("end",()=>{try{sj(res,200,o2a(JSON.parse(data),cfg.displayModel))}catch(e){se(res,502,e.message)}})});pr.on("timeout",()=>{pr.destroy();se(res,504,"timeout")});pr.on("error",e=>se(res,502,e.message));pr.write(postData);pr.end()}
function su(oar,res,cfg){const postData=JSON.stringify(oar),u=new URL(cfg.upstream);const opts={hostname:u.hostname,port:u.port||443,path:u.pathname+u.search,method:"POST",headers:{Authorization:"Bearer "+cfg.apiKey,"Content-Type":"application/json","Content-Length":Buffer.byteLength(postData),"Accept":"text/event-stream"},timeout:300000};const pr=https.request(opts,prs=>{res.writeHead(prs.statusCode,{"Content-Type":"text/event-stream","Cache-Control":"no-cache","Connection":"keep-alive","X-Accel-Buffering":"no","Access-Control-Allow-Origin":"*"});res.write("event: content_block_start\ndata: "+JSON.stringify({type:"content_block_start",index:0,content_block:{type:"text",text:""}})+"\n\n");let buf="",sr="end_turn";prs.on("data",chunk=>{buf+=chunk.toString();const lines=buf.split("\n");buf=lines.pop();for(const line of lines){if(!line.startsWith("data: "))continue;const d=line.substring(6);if(d.trim()==="[DONE]"){res.write("event: content_block_stop\ndata: "+JSON.stringify({type:"content_block_stop",index:0})+"\n\n");res.write("event: message_delta\ndata: "+JSON.stringify({type:"message_delta",delta:{stop_reason:sr},usage:{output_tokens:0}})+"\n\n");res.write("event: message_stop\ndata: "+JSON.stringify({type:"message_stop"})+"\n\n");res.end();return}try{const parsed=JSON.parse(d),delta=parsed.choices&&parsed.choices[0]&&parsed.choices[0].delta;if(!delta)continue;if(delta.content){res.write("event: content_block_delta\ndata: "+JSON.stringify({type:"content_block_delta",index:0,delta:{type:"text_delta",text:delta.content}})+"\n\n")}if(parsed.choices&&parsed.choices[0].finish_reason){const fr=parsed.choices[0].finish_reason;sr=fr==="length"?"max_tokens":fr==="tool_calls"?"tool_use":"end_turn"}}catch(e){}}});prs.on("end",()=>res.end());prs.on("error",()=>res.end())});pr.on("timeout",()=>{pr.destroy();res.end()});pr.on("error",()=>res.end());pr.write(postData);pr.end()}
server.listen(PORT,"0.0.0.0",()=>{console.log("[proxy] listening on 0.0.0.0:"+PORT);console.log("upstream="+cfg.upstream+" model="+cfg.model)});
server.on("error",err=>{console.error("Server error:",err.message);process.exit(1)});
process.on("SIGTERM",()=>server.close(()=>process.exit(0)));
process.on("SIGINT",()=>server.close(()=>process.exit(0)));
