# Khy-OS 一键修复脚本（PowerShell）

Write-Host "================================================" -ForegroundColor Cyan
Write-Host " Khy-OS 全局命令配置脚本" -ForegroundColor Cyan
Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""

# Resolve repo root from this script's own location: <root>\scripts\setup\
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$khyEntry = Join-Path $repoRoot 'services\backend\bin\khy.js'

if (!(Test-Path -Path $khyEntry)) {
    Write-Host "✗ 未找到 CLI 入口: $khyEntry" -ForegroundColor Red
    Write-Host "  请从 khy-os 仓库的 scripts\setup\ 目录运行本脚本。" -ForegroundColor Yellow
    exit 1
}
Write-Host "✓ 项目根目录: $repoRoot" -ForegroundColor Green
Write-Host ""

# 检查 PowerShell 配置文件
if (!(Test-Path -Path $PROFILE)) {
    Write-Host "✓ 创建 PowerShell 配置文件..." -ForegroundColor Yellow
    New-Item -ItemType File -Path $PROFILE -Force | Out-Null
}

# 检查是否已经配置
$profileContent = Get-Content -Path $PROFILE -ErrorAction SilentlyContinue
if ($profileContent -match "khy-os") {
    Write-Host "⚠ 检测到已存在 khy 配置" -ForegroundColor Yellow
    $overwrite = Read-Host "是否覆盖? (y/n)"
    if ($overwrite -ne "y") {
        Write-Host "✗ 已取消" -ForegroundColor Red
        exit
    }
}

# 添加 khy 函数
Write-Host "✓ 添加 khy 全局命令..." -ForegroundColor Green
$khyFunction = @"

# ================================================
# Khy-OS Global Command
# Auto-generated by setup script
# ================================================
function khy {
    node "$khyEntry" `$args
}

# Alias
Set-Alias -Name khyos -Value khy -ErrorAction SilentlyContinue

Write-Host "Khy-OS Ready! Use 'khy --help' to start." -ForegroundColor Green
"@

Add-Content -Path $PROFILE -Value $khyFunction

Write-Host ""
Write-Host "================================================" -ForegroundColor Green
Write-Host " ✓ 配置完成！" -ForegroundColor Green
Write-Host "================================================" -ForegroundColor Green
Write-Host ""
Write-Host "下一步：" -ForegroundColor Yellow
Write-Host "  1. 重新打开 PowerShell 窗口" -ForegroundColor White
Write-Host "  2. 或运行: . `$PROFILE" -ForegroundColor White
Write-Host "  3. 测试: khy --version" -ForegroundColor White
Write-Host ""

# 询问是否立即重载
$reload = Read-Host "是否立即重载配置? (y/n)"
if ($reload -eq "y") {
    . $PROFILE
    Write-Host ""
    Write-Host "✓ 配置已重载！运行 'khy --version' 测试" -ForegroundColor Green
}
