"""Insert a test admin user directly into the DB."""
import os
import sqlite3
import hashlib

# khyquant DB lives inside the project data home (repo root/.khy/khyquant/data/)
DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', '.khy', 'khyquant', 'data', 'khy-quant.db')
PASSWORD = "testpass123"

# Hash the password with bcrypt-compatible format for testing
# We need bcrypt hash - let's just insert a simple bcrypt hash for testing
# The real one is generated by bcryptjs with 10 rounds

con = sqlite3.connect(DB_PATH)
cur = con.cursor()

# Insert user with a bcrypt hash of 'testpass123'
# $2b$10$ is bcrypt with 10 rounds
# We need a real bcrypt hash - generate via Python bcrypt or use a known hash
import bcrypt
hashed = bcrypt.hashpw(PASSWORD.encode(), bcrypt.gensalt(rounds=10)).decode()

cur.execute(
    'INSERT INTO users (username, email, password, role, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, datetime("now"), datetime("now"))',
    ('qiqiaoban', 'qiqiaoban@khy-quant.com', hashed, 'admin', 'active')
)
con.commit()
print(f"Inserted user 'qiqiaoban' with bcrypt hash")

# Verify
cur.execute('SELECT id, username FROM users')
for r in cur.fetchall():
    print(f"  id={r[0]} username={r[1]}")

con.close()
